image: atlassian/default-image:3

definitions:
  steps:
    - step: &deploy
        name: deploy
        script:
          - pipe: atlassian/ssh-run:0.4.0
            variables:
              SSH_USER: $USER
              SERVER: $AWS_SERVER
              MODE: 'command'
              COMMAND:
                >-
                cd /var/www/${WORK_DIR:=dfs}/das &&
                git fetch --prune &&
                git checkout $BITBUCKET_BRANCH &&
                git pull &&
                cd ../docker &&
                docker-compose exec -T das composer install &&
                docker-compose exec -T das composer check-build &&
                docker-compose exec -T das php artisan down &&
                docker-compose exec -T das php artisan cache:clear &&
                docker-compose exec -T das php artisan config:cache &&
                docker-compose exec -T das php artisan route:cache &&
                docker-compose exec -T das php artisan up &&
                docker-compose exec -T das php artisan test
pipelines:
  custom:
    deploy-to-dev-aws:
      - step:
          <<: *deploy
          deployment: aws_development
          name: deploy to aws development
    deploy-to-stage-aws:
      - step:
          <<: *deploy
          deployment: aws_stage
          name: deploy to aws stage
  branches:
    develop:
      - step:
          <<: *deploy
          deployment: aws_development
          name: deploy to aws development
    master:
      - step:
          <<: *deploy
          deployment: aws_development
          name: deploy to aws development
    '{release/*}':
      - step:
          <<: *deploy
          deployment: aws_development
          name: deploy to aws development